name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, nv-palladium]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check Rust version
        run: |
          rustc --version
          cargo --version

      - name: Check project structure
        run: |
          echo "=== Project structure ==="
          find src -name "*.rs" -type f || echo "No src directory found"
          echo "=== Cargo.toml content ==="
          cat Cargo.toml || echo "No Cargo.toml found"

      - name: Build (debug)
        run: |
          echo "=== Building debug ==="
          cargo build --verbose
          echo "=== Debug build contents ==="
          ls -la target/debug/ || true

      - name: Build (release)
        run: |
          echo "=== Building release ==="
          cargo build --release --verbose
          echo "=== Release build contents ==="
          ls -la target/release/ || true
          echo "=== Target-specific release contents ==="
          ls -la target/x86_64-unknown-linux-gnu/release/ || true
          echo "=== Looking for binaries ==="
          find target/ -name "oxygen" -type f -executable || true

      - name: Test
        run: cargo test --verbose

      - name: Verify binary exists
        run: |
          # Check multiple possible locations
          BINARY_FOUND=false
          
          # Check standard location first
          if [[ -f "target/release/oxygen" ]]; then
            echo "✓ Found oxygen binary at target/release/oxygen"
            ./target/release/oxygen --version || echo "Binary exists but failed to run"
            BINARY_FOUND=true
          elif [[ -f "target/x86_64-unknown-linux-gnu/release/oxygen" ]]; then
            echo "✓ Found oxygen binary at target/x86_64-unknown-linux-gnu/release/oxygen"
            ./target/x86_64-unknown-linux-gnu/release/oxygen --version || echo "Binary exists but failed to run"
            BINARY_FOUND=true
          else
            echo "✗ No oxygen binary found"
            echo "Checking all possible locations..."
            find target/ -name "oxygen" -type f -executable 2>/dev/null || true
            echo "Available files in target/release/:"
            ls -la target/release/ 2>/dev/null || true
            echo "Available files in target/x86_64-unknown-linux-gnu/release/:"
            ls -la target/x86_64-unknown-linux-gnu/release/ 2>/dev/null || true
          fi
          
          if [[ "$BINARY_FOUND" == "false" ]]; then
            exit 1
          fi
